name: Bicho Update Semanal

on:
  schedule:
    - cron: '0 0 * * 2' # Meia-noite UTC de Terça-feira
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: pip install -r requirements.txt

      - name: Correr Migrações e Atualizar Dados
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FLASK_APP: api.py
        run: |
          echo "A verificar se a Base de Dados precisa de ser criada ou atualizada..."
          flask db upgrade
          
          echo "A correr o Pipeline de Previsões..."
          python bicho_ppl.py
